### ISSUE TITLE
Web Notification not working with service worker.

### ISSUE THREAD

**Issue by Imdavyking** [pichillilorenzo/flutter_inappwebview_examples#3]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
|----------------------| ------------- |
| Project Example Name |               |
| Flutter version      |         3.3.3      |
| Plugin version       |         6.0.21      |
| Android version      |               |
| iOS version          |               |
| macOS version        |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 
```dart
 _controller.addJavaScriptHandler(
                  handlerName: 'Notification.show',
                  callback: (arguments) {
                    if (_controller != null) {
                      final notification =
                          WebNotification.fromJson(arguments[0], _controller);
                      onShowNotification(notification);
                    }
                  },
                );
```

``` javascript
// call notification with service worker
navigator.serviceWorker.register('service-worker.js');
  Notification.requestPermission(function(result) {

    if (result === 'granted') {
              console.log(result + 'slsl');
      navigator.serviceWorker.ready.then(function(registration) {
        registration.showNotification('Notification with ServiceWorker');
      });
    }
  });
```

**Current behavior:** 
 'Notification.show' not being called
## Steps to reproduce

1. This
2. Than that
3. Then

## Stacktrace/Logcat

**Comment by pichillilorenzo** [comment]
The `ServiceWorkerRegistration` API  is not implemented in the example.

What is implemented is just the `Notification` object.
If you want to use my project example, instead of using `registration.showNotification`, use just `Notification`:
```javascript
const notification = new Notification('Notification Title', {
  body: 'Notification Body!',
  icon: 'https://picsum.photos/250?image=9',
  vibrate: [200, 100, 200]}
);
```

Otherwise, implement by yourself the `ServiceWorkerRegistration.showNotification` method by updating the JavaScript used to create the "polyfill".

Maybe, I can try to look at this and add an example implementation, but these are just sample projects.

However, as I already said, these projects are just examples, you shouldn't expect them to be 100% completed or that they cover fully a specific feature. You can use them as a starting point for your projects and use cases, nothing more.

**Comment by pichillilorenzo** [comment]
@Imdavyking I have updated the [JavaScript code implementation (assets/web_notification.js)](https://github.com/pichillilorenzo/flutter_inappwebview_examples/blob/main/web_notification/assets/web_notification.js) to support also the `ServiceWorkerRegistration.showNotification` and `ServiceWorkerRegistration.getNotifications` methods and `Notification.requestPermission(callback)` using the callback instead of the promise version.

Now your implementation should work.

**Comment by Imdavyking** [comment]
Thank you so so much...I really appreciate
