### ISSUE TITLE
Examples needs to be updated

### ISSUE THREAD

**Issue by p-Osteen** [pichillilorenzo/flutter_inappwebview_examples#7]
- The method 'setWebContentsDebuggingEnabled' isn't defined for the type 'InAppWebViewController'. 
Try correcting the name to the name of an existing method, or defining a method named 'setWebContentsDebuggingEnabled'.
- The method 'setSettings' isn't defined for the type 'InAppWebViewController'. 
Try correcting the name to the name of an existing method, or defining a method named 'setSettings'.
- The method 'InAppWebViewSettings' isn't defined for the type '_MyAppState'.
Try correcting the name to the name of an existing method, or defining a method named 'InAppWebViewSettings'.

**Comment by vousmeevoyez** [comment]
@pichillilorenzo

**Comment by kelvindesman** [comment]
@paulpoyyayil make sure your `pubspec.yaml` used `6.0.0-beta.22` because by default it install the latest stable `5.7.2+3`.

This repository use the prerelease version that's why you getting error since the one you are using is the older version.

https://inappwebview.dev/docs/migration-guide/
https://github.com/pichillilorenzo/flutter_inappwebview_examples/blob/main/third_party_oauth_user_sign_in/pubspec.yaml
